import { StaticSite, StaticSiteArgs } from '.sst/platform/src/components/aws';
import { Component } from '.sst/platform/src/components/component';
import { Link } from '.sst/platform/src/components/link';
import { ComponentResourceOptions } from '@pulumi/pulumi';

export class GigaChadSite extends Component implements Link.Linkable {
    private staticSite: StaticSite;

    constructor(
        name: string,
        args: StaticSiteArgs = {},
        opts: ComponentResourceOptions = {},
    ) {
        super(__pulumiType, name, args, opts);

        this.staticSite = new StaticSite(`${name}-static`, args, opts);
    }

    /**
     * The URL of the website.
     *
     * If the `domain` is set, this is the URL with the custom domain.
     * Otherwise, it's the autogenerated CloudFront URL.
     */
    public get url() {
        return this.staticSite.url;
    }

    /**
     * The underlying [resources](/docs/components/#nodes) this component creates.
     */
    public get nodes() {
        return {
            /**
             * The StaticSite that handles the static requests.
             */
            staticSite: this.staticSite,
        };
    }

    /** @internal */
    public getSSTLink() {
        return {
            properties: {
                url: this.url,
            },
        };
    }
}

const __pulumiType = 'sst:aws:GigaChadSite';
// @ts-expect-error
StaticSite.__pulumiType = __pulumiType;
