//! Guided setup using the same repository evidence as tool execution.

use std::io::{BufRead, Write};
use std::path::Path;

use super::{RepositoryDiscovery, ScopeConfig};

/// Guides setup in `root`, previews the configuration, and creates it on approval.
/// Native tool configuration is left untouched. No tools are executed or installed.
///
/// # Errors
///
/// * If `clippier.toml` already exists
/// * If repository discovery, terminal input/output, or file creation fails
/// * If input ends before the user completes setup
pub fn initialize(
    root: &Path,
    input: &mut impl BufRead,
    output: &mut impl Write,
) -> std::io::Result<()> {
    let destination = root.join("clippier.toml");
    if destination.try_exists()? {
        return Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!(
                "{} already exists; leaving it unchanged",
                destination.display()
            ),
        ));
    }
    let mut inventory = RepositoryDiscovery::inventory(root, &ScopeConfig::default())?;
    let evidence = inventory.tool_evidence();
    writeln!(output, "Repository: {}", root.canonicalize()?.display())?;
    writeln!(
        output,
        "Native configs remain authoritative. Tools will not be installed or run."
    )?;
    writeln!(
        output,
        "Selected tools use automatic ownership; overlapping formatters may need runner.tools policies."
    )?;
    let mut selected = Vec::new();
    let mut skipped = Vec::new();
    for (name, evidence) in evidence {
        writeln!(
            output,
            "\n{name}: {:?} ({})",
            evidence.kind,
            evidence.path.display()
        )?;
        if confirm(input, output, &format!("Enable {name}?"), true)? {
            selected.push(name);
        } else {
            skipped.push(name);
        }
    }
    if selected.is_empty() {
        writeln!(
            output,
            "No tools selected. Automatic discovery remains enabled for tools not skipped."
        )?;
    }
    let required = confirm(
        input,
        output,
        "Require selected tools to be installed (recommended for CI)?",
        true,
    )?;
    let config = render_config(&selected, &skipped, required);
    writeln!(output, "\n--- clippier.toml ---\n{config}--- end ---")?;
    if !confirm(input, output, "Create clippier.toml?", false)? {
        writeln!(output, "Cancelled; no files written.")?;
        return Ok(());
    }
    // create_new also protects against a file appearing while prompts are open.
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&destination)?;
    file.write_all(config.as_bytes())?;
    writeln!(
        output,
        "Created {}. Review tool selection with clippier check --list and clippier fmt --list.",
        destination.display()
    )?;
    Ok(())
}

fn confirm(
    input: &mut impl BufRead,
    output: &mut impl Write,
    question: &str,
    default: bool,
) -> std::io::Result<bool> {
    loop {
        write!(
            output,
            "{question} {} ",
            if default { "[Y/n]" } else { "[y/N]" }
        )?;
        output.flush()?;
        let mut answer = String::new();
        if input.read_line(&mut answer)? == 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                "Setup input ended; configuration not written",
            ));
        }
        match answer.trim().to_ascii_lowercase().as_str() {
            "" => return Ok(default),
            "y" | "yes" => return Ok(true),
            "n" | "no" => return Ok(false),
            _ => writeln!(output, "Please answer yes or no.")?,
        }
    }
}

fn render_config(selected: &[String], skipped: &[String], required: bool) -> String {
    let mut runner = toml::map::Map::new();
    runner.insert(
        "required".into(),
        toml::Value::Array(
            if required { selected } else { &[] }
                .iter()
                .cloned()
                .map(toml::Value::String)
                .collect(),
        ),
    );
    runner.insert(
        "skip".into(),
        toml::Value::Array(skipped.iter().cloned().map(toml::Value::String).collect()),
    );
    let mut document = toml::map::Map::new();
    document.insert("runner".into(), toml::Value::Table(runner));
    format!(
        "# Generated by clippier init. Native tool configs remain authoritative.\n# Tools not skipped remain eligible for automatic discovery.\n{}",
        toml::to_string(&document).expect("string arrays serialize as TOML")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(feature = "format")]
    fn setup_creates_valid_config_and_preserves_existing_files() {
        let root = tempfile::tempdir().unwrap();
        std::fs::write(
            root.path().join("Cargo.toml"),
            "[package]\nname = 'example'\nversion = '0.1.0'\n",
        )
        .unwrap();
        let mut inventory =
            RepositoryDiscovery::inventory(root.path(), &ScopeConfig::default()).unwrap();
        let evidence = inventory.tool_evidence();
        assert!(evidence.contains_key("rustfmt"));
        assert_eq!(inventory.diagnostics().recursive_walks, 1);
        let responses = format!("{}y\ny\n", "y\n".repeat(evidence.len()));
        let mut output = Vec::new();
        initialize(root.path(), &mut responses.as_bytes(), &mut output).unwrap();
        let path = root.path().join("clippier.toml");
        let contents = std::fs::read_to_string(&path).unwrap();
        let value: toml::Value = toml::from_str(&contents).unwrap();
        let config: super::super::ToolsConfig = value["runner"].clone().try_into().unwrap();
        assert!(config.required.contains(&"rustfmt".to_owned()));
        assert_eq!(
            initialize(root.path(), &mut &b""[..], &mut output)
                .unwrap_err()
                .kind(),
            std::io::ErrorKind::AlreadyExists
        );
        assert_eq!(std::fs::read_to_string(path).unwrap(), contents);
    }

    #[test]
    #[cfg(feature = "format")]
    fn cancellation_does_not_write() {
        let root = tempfile::tempdir().unwrap();
        initialize(root.path(), &mut &b"n\nn\n"[..], &mut Vec::new()).unwrap();
        assert!(!root.path().join("clippier.toml").exists());
    }

    #[test]
    fn generated_config_round_trips() {
        let text = render_config(&["rustfmt".into()], &["prettier".into()], true);
        let value: toml::Value = toml::from_str(&text).unwrap();
        let config: super::super::ToolsConfig = value["runner"].clone().try_into().unwrap();
        assert_eq!(config.required, ["rustfmt"]);
        assert_eq!(config.skip, ["prettier"]);
    }

    #[test]
    fn confirmation_retries_and_handles_eof() {
        let mut output = Vec::new();
        assert!(confirm(&mut &b"invalid\nyes\n"[..], &mut output, "Continue?", false).unwrap());
        assert!(!confirm(&mut &b"\n"[..], &mut output, "Continue?", false).unwrap());
        assert_eq!(
            confirm(&mut &b""[..], &mut output, "Continue?", false)
                .unwrap_err()
                .kind(),
            std::io::ErrorKind::UnexpectedEof
        );
    }
}
