//! Example implementation demonstrating async service usage.
//!
//! This module provides a reference implementation showing how to use the
//! [`moosicbox_async_service`](crate) macros to create an async service with
//! command processing and lifecycle management.

use moosicbox_async_service::Arc;
use switchy_async::sync::RwLock;
use strum_macros::AsRefStr;

/// Commands that can be sent to the example service.
///
/// This enum demonstrates how to define commands for an async service.
/// Each variant represents an action that the service can process.
#[derive(Debug, AsRefStr)]
pub enum Command {
    /// Establishes a connection.
    ///
    /// This is a placeholder command demonstrating the pattern.
    Connect {},
}

impl std::fmt::Display for Command {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_ref())
    }
}

/// Service module containing the generated async service types.
///
/// This module is generated by the [`async_service!`](crate::async_service) macro
/// and contains all the necessary types for running the service including:
/// * `Service` - The main service struct
/// * `Handle` - A handle for sending commands to the service
/// * `Processor` - The trait to implement for command processing logic
/// * `Commander` - Trait for interacting with the service
/// * `Error` - Error type for service operations
pub mod service {
    moosicbox_async_service::async_service!(super::Command, super::Context);
}

#[moosicbox_async_service::async_trait]
impl service::Processor for service::Service {
    type Error = service::Error;

    async fn on_start(&mut self) -> Result<(), Self::Error> {
        Ok(())
    }

    async fn on_shutdown(_ctx: Arc<RwLock<Context>>) -> Result<(), Self::Error> {
        Ok(())
    }

    async fn process_command(
        _ctx: Arc<RwLock<Context>>,
        command: Command,
    ) -> Result<(), Self::Error> {
        log::debug!("process_command command={command}");
        match command {
            Command::Connect {} => {
                log::debug!("Received Connect command");
            }
        }
        Ok(())
    }
}

/// Context for the example service.
///
/// This struct holds the shared state for the service. It is wrapped in
/// `Arc<RwLock<Context>>` by the service and can be accessed from command
/// processing functions.
pub struct Context {}
