//! OpenAPI example for MoosicBox web server.
//!
//! This example demonstrates how to create and serve an OpenAPI specification
//! using the MoosicBox web server framework with utoipa integration.
//!
//! # Features
//!
//! * Creates an OpenAPI specification with example endpoints
//! * Serves the specification through the `/openapi` path
//! * Demonstrates path definition using the `path!` macro
//! * Includes example endpoint with parameters and response documentation

use moosicbox_web_server::{HttpResponse, Scope, path, utoipa};
use utoipa::{OpenApi as _, openapi::OpenApi};

/// Entry point for the OpenAPI example web server.
///
/// Initializes logging, configures CORS, sets up the OpenAPI specification,
/// and starts the web server with example endpoints.
///
/// # Errors
///
/// * Logging initialization fails
/// * Server startup encounters an error
///
/// # Panics
///
/// * Panics if the global `OPENAPI` `RwLock` is poisoned (another thread panicked while holding the lock)
#[switchy_async::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    moosicbox_logging::init(None, None)?;

    let cors = moosicbox_web_server::cors::Cors::default()
        .allow_any_origin()
        .allow_any_method()
        .allow_any_header()
        .expose_any_header();

    *moosicbox_web_server::openapi::OPENAPI.write().unwrap() = Some(init());

    let server = moosicbox_web_server::WebServerBuilder::new()
        .with_cors(cors)
        .with_scope(moosicbox_web_server::openapi::bind_services(Scope::new(
            "/openapi",
        )))
        // The order matters here. Make sure to add the root scope last
        .with_scope(Scope::new("").get("/example", |req| {
            let path = req.path().to_string();
            let query = req.query_string().to_string();
            Box::pin(async move {
                Ok(HttpResponse::ok()
                    .with_body(format!("hello, world! path={path} query={query}",)))
            })
        }))
        .build();

    server.start().await;

    Ok(())
}

/// Static OpenAPI specification for the example endpoint.
///
/// This lazy-initialized specification defines the `/example` endpoint with:
/// * Tags for API categorization
/// * Path definitions for the example endpoint (from [`GET_EXAMPLE_PATH`])
/// * Component schemas
///
/// The specification is constructed using the utoipa builder pattern and is
/// merged with other API definitions in the [`init`] function.
///
/// # Note
///
/// The `GET_EXAMPLE_PATH` static is generated by the `path!` macro invocation
/// at the end of this file, which creates a `LazyLock<PathItem>` containing
/// the complete path specification for the `/example` endpoint with GET method,
/// parameters, and response definitions.
pub static API: std::sync::LazyLock<utoipa::openapi::OpenApi> = std::sync::LazyLock::new(|| {
    OpenApi::builder()
        .tags(Some([utoipa::openapi::Tag::builder()
            .name("Example")
            .build()]))
        .paths(
            utoipa::openapi::Paths::builder()
                .path("/example", GET_EXAMPLE_PATH.clone())
                .build(),
        )
        .components(Some(utoipa::openapi::Components::builder().build()))
        .build()
});

/// Base OpenAPI documentation structure.
///
/// This empty structure serves as the foundation for the OpenAPI specification,
/// which is extended with custom API definitions through the `nest_api` function
/// in the [`init`] function.
#[derive(utoipa::OpenApi)]
#[openapi()]
struct ApiDoc;

/// Initializes and returns the complete OpenAPI specification.
///
/// This function combines the base API documentation from `ApiDoc` with
/// the custom [`API`] specification, nesting them together to create a
/// complete OpenAPI document.
///
/// # Returns
///
/// Returns a fully constructed [`OpenApi`] specification that includes all
/// endpoint definitions, schemas, and metadata for the example web server.
#[must_use]
pub fn init() -> OpenApi {
    #[allow(unused)]
    fn nest_api(api: OpenApi, path: &str, mut nested: OpenApi) -> OpenApi {
        nested.paths.paths.iter_mut().for_each(|(path, item)| {
            item.options.iter_mut().for_each(|operation| {
                operation.operation_id = Some(path.to_owned());
            });
        });

        api.nest(path, nested)
    }

    nest_api(ApiDoc::openapi(), "", API.clone())
}

path!(
    GET,
    example,
    utoipa::openapi::PathItem::builder()
        .operation(
            HttpMethod::Get,
            Operation::builder()
                .description(Some("description"))
                .tags(Some(["Tag1", "Tag2"]))
                .parameter(
                    Parameter::builder()
                        .name("moosicbox-profile")
                        .parameter_in(ParameterIn::Header)
                        .description(Some("MoosicBox profile"))
                        .required(Required::True)
                        .schema(Some(utoipa::schema!(String))),
                )
                .parameter(
                    Parameter::builder()
                        .name("magicToken")
                        .parameter_in(ParameterIn::Path)
                        .description(Some("The magic token to fetch the credentials for"))
                        .required(Required::True)
                        .schema(Some(utoipa::schema!(String))),
                )
                .responses(
                    Responses::builder()
                        .response(
                            "200",
                            RefOr::T(
                                Response::builder()
                                    .description("The credentials for the magic token")
                                    .content(
                                        "application/json",
                                        Content::builder()
                                            .schema(Some(utoipa::schema!(Value)))
                                            .build(),
                                    )
                                    .build(),
                            ),
                        )
                        .build(),
                ),
        )
        .build()
);
