//! Tauri bundled application service for `MoosicBox`.
//!
//! This crate provides the bundled Tauri application that runs the `MoosicBox`
//! server embedded within a desktop application. It manages the lifecycle of
//! the embedded server, including startup, shutdown, and event handling.
//!
//! # Example
//!
//! ```rust,no_run
//! use moosicbox_app_tauri_bundled::{Context, service};
//!
//! # fn main() {
//! let runtime_handle = moosicbox_async_service::runtime::Handle::current();
//! let ctx = Context::new(&runtime_handle).expect("Failed to initialize bundled server");
//! let service = service::Service::new(ctx);
//! let _handle = service.start();
//! # }
//! ```

#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
#![allow(clippy::multiple_crate_versions)]

use moosicbox_async_service::{Arc, sync::RwLock};
use moosicbox_config::AppType;
pub use moosicbox_server::{
    BundledReadyServer as ReadyServer, BundledStartupError as StartupError,
};
use strum_macros::AsRefStr;
use switchy_async::sync::oneshot;
use tauri::RunEvent;

/// Commands for the Tauri bundled app service.
///
/// These commands control the lifecycle and event handling of the embedded
/// `MoosicBox` server within the Tauri application.
///
/// # Examples
///
/// ```rust,no_run
/// use moosicbox_app_tauri_bundled::Command;
/// use switchy_async::sync::oneshot;
///
/// let (sender, receiver) = oneshot::channel();
/// let cmd = Command::WaitForStartup { sender };
/// ```
#[derive(Debug, AsRefStr)]
pub enum Command {
    /// Process a Tauri run event.
    RunEvent { event: Arc<RunEvent> },
    /// Wait for the server to complete startup.
    WaitForStartup {
        sender: oneshot::Sender<Result<ReadyServer, StartupError>>,
    },
    /// Wait for the server to complete shutdown.
    WaitForShutdown { sender: oneshot::Sender<()> },
}

impl std::fmt::Display for Command {
    /// Formats the command as a string using its `AsRefStr` representation.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_ref())
    }
}

/// Async service infrastructure for managing the Tauri bundled app lifecycle.
///
/// This module provides the core service types for managing the embedded `MoosicBox`
/// server within the Tauri application. It includes:
///
/// * `Service` - Main service struct for lifecycle management
/// * `Handle` - Cloneable handle for sending commands to the service
/// * `Processor` - Trait implemented by the service for command processing
///
/// The module is generated by the `async_service!` macro and provides standard
/// service patterns for command processing, startup, and shutdown.
pub mod service {
    moosicbox_async_service::async_service!(super::Command, super::Context);
}

#[moosicbox_async_service::async_trait]
impl service::Processor for service::Service {
    type Error = service::Error;

    /// Called when the service starts.
    ///
    /// # Errors
    ///
    /// * Currently always succeeds
    async fn on_start(&mut self) -> Result<(), Self::Error> {
        Ok(())
    }

    /// Cancels the bundled server if the command service stops first.
    ///
    /// Cancels and settles the bundled server if the command service stops first.
    ///
    /// # Errors
    ///
    /// * If the server task returns an error other than cancellation
    async fn on_shutdown(ctx: Arc<RwLock<Context>>) -> Result<(), Self::Error> {
        let handle = ctx.read().await.server_handle.clone();
        handle.abort();
        if let Err(error) = handle.wait().await
            && error.kind() != std::io::ErrorKind::Interrupted
        {
            return Err(error.into());
        }
        Ok(())
    }

    /// Processes commands for the Tauri bundled app service.
    ///
    /// # Errors
    ///
    /// * `WaitForShutdown` - Returns error if the server handle fails to join or if an IO error occurs in the embedded server
    async fn process_command(
        ctx: Arc<RwLock<Context>>,
        command: Command,
    ) -> Result<(), Self::Error> {
        log::debug!("process_command: command={command}");
        match command {
            Command::RunEvent { event } => {
                log::debug!("process_command: Received RunEvent command");
                let response = ctx.read().await.handle_event(&event);
                if let Err(e) = response {
                    log::error!("process_command: Failed to handle event: {e:?}");
                }
            }
            Command::WaitForStartup { sender } => {
                let result = ctx.write().await.startup.wait().await;
                if let Err(e) = sender.send(result) {
                    log::error!("process_command: Failed to send WaitForStartup response: {e:?}");
                }
            }
            Command::WaitForShutdown { sender } => {
                let handle = ctx.read().await.server_handle.clone();
                handle.wait().await?;
                if let Err(e) = sender.send(()) {
                    log::error!("process_command: Failed to send WaitForShutdown response: {e:?}");
                }
            }
        }
        Ok(())
    }
}

/// Context for the Tauri bundled app service.
///
/// Holds the runtime state of the embedded server, including its join handle
/// and startup notification channel.
pub struct Context {
    server_handle: moosicbox_server::BundledServerTask,
    startup: moosicbox_server::BundledStartup,
}

impl Context {
    /// Creates a new `Context` and starts the embedded server.
    ///
    /// # Panics
    ///
    /// * If the default download path cannot be determined
    /// * If the download directory cannot be created
    /// * If the download path contains invalid UTF-8
    /// * If database profiles cannot be accessed
    /// * If scan paths cannot be added to the database
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// let runtime_handle = moosicbox_async_service::runtime::Handle::current();
    /// let context = moosicbox_app_tauri_bundled::Context::new(&runtime_handle)?;
    ///
    /// let _ = context;
    /// ```
    /// # Errors
    ///
    /// * If the default download path cannot be determined or created
    /// * If a loopback listener cannot be reserved
    /// * If the selected listener address cannot be read
    pub fn new(handle: &moosicbox_async_service::runtime::Handle) -> Result<Self, StartupError> {
        let downloads_path = moosicbox_downloader::get_default_download_path()
            .map_err(|error| StartupError::new(error.to_string()))?;
        std::fs::create_dir_all(&downloads_path)
            .map_err(|error| StartupError::new(error.to_string()))?;

        let (startup, startup_sender) = moosicbox_server::BundledStartup::pending();
        let (listener, ready) = moosicbox_server::bind_bundled_listener()?;
        let port = listener
            .local_addr()
            .map_err(|error| StartupError::new(error.to_string()))?
            .port();
        let startup_ready = ready;
        let failure_sender = startup_sender.clone();

        let server_handle =
            handle.spawn_with_name("moosicbox_app_tauri_bundled server", async move {
                let result = moosicbox_server::run_basic_with_listener(
                    AppType::App,
                    "127.0.0.1",
                    port,
                    None,
                    Some(listener),
                    move |_| {
                        switchy_async::runtime::Handle::current().spawn_with_name(
                            "moosicbox_app_tauri_bundled: create_download_location",
                            async move {
                                let downloads_path_str = downloads_path.to_str().unwrap();

                                for profile in switchy_database::profiles::PROFILES.names() {
                                    let db =
                                        switchy_database::profiles::PROFILES.get(&profile).unwrap();
                                    moosicbox_scan::db::add_scan_path(&db, downloads_path_str)
                                        .await
                                        .unwrap();
                                }

                                moosicbox_profiles::events::on_profiles_updated_event(
                                    move |added, _removed| {
                                        let added = added.to_vec();
                                        let downloads_path = downloads_path.clone();

                                        Box::pin(async move {
                                            let downloads_path_str =
                                                downloads_path.to_str().unwrap();

                                            for profile in &added {
                                                let db = switchy_database::profiles::PROFILES
                                                    .get(profile)
                                                    .unwrap();
                                                moosicbox_scan::db::add_scan_path(
                                                    &db,
                                                    downloads_path_str,
                                                )
                                                .await
                                                .unwrap();
                                            }

                                            Ok(())
                                        })
                                    },
                                )
                                .await;
                            },
                        );

                        log::info!("App server listening at {}", startup_ready.endpoint);
                        startup_sender.ready(startup_ready);
                    },
                )
                .await;
                if let Err(error) = &result {
                    failure_sender.failed(error.to_string());
                }
                result
            });

        Ok(Self {
            server_handle: moosicbox_server::BundledServerTask::new(server_handle),
            startup,
        })
    }

    /// Returns shared ownership of the bundled server task.
    #[must_use]
    pub fn server_task(&self) -> moosicbox_server::BundledServerTask {
        self.server_handle.clone()
    }

    /// Handles a Tauri run event, initiating shutdown on exit requests.
    ///
    /// # Errors
    ///
    /// * Returns error if shutdown fails (currently always succeeds)
    pub fn handle_event(&self, event: &Arc<RunEvent>) -> Result<(), std::io::Error> {
        if let tauri::RunEvent::ExitRequested { .. } = **event {
            self.shutdown()?;
        }
        Ok(())
    }

    /// Shuts down the embedded server by aborting its runtime handle.
    ///
    /// # Errors
    ///
    /// * Currently always succeeds, but returns `Result` for API consistency and to allow for future error conditions
    pub fn shutdown(&self) -> Result<(), std::io::Error> {
        self.server_handle.abort();
        Ok(())
    }
}

#[cfg(test)]
mod tests {

    #[switchy_async::test]
    async fn startup_channel_closure_is_an_error() {
        let (mut startup, sender) = moosicbox_server::BundledStartup::pending();
        drop(sender);

        let error = startup.wait().await.unwrap_err();

        assert!(error.to_string().contains("startup channel closed"));
    }

    #[switchy_async::test]
    async fn startup_channel_preserves_server_failure() {
        let (mut startup, sender) = moosicbox_server::BundledStartup::pending();
        sender.failed("migration failed");

        let error = startup.wait().await.unwrap_err();

        assert_eq!(
            error.to_string(),
            "Bundled server failed to start: migration failed"
        );
    }
}
