#![cfg_attr(feature = "fail-on-warnings", deny(warnings))]
#![warn(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
#![allow(clippy::multiple_crate_versions)]

//! Types and trait for TOML configuration documentation schemas.
//!
//! This crate defines the `ConfigDocSchema` trait and `FieldDoc` type that are
//! implemented by the `#[derive(ConfigDoc)]` proc macro. The docs site uses
//! these to generate the configuration reference page.

use std::collections::BTreeMap;

/// Nested schema metadata for a field that expands into dotted sub-keys.
#[derive(Clone)]
pub enum NestedFieldDoc {
    /// Inline nested struct, expanded as `<parent>.<child>`.
    Inline {
        /// Child field docs from the nested schema.
        fields: Vec<FieldDoc>,
        /// Default values keyed by child field name.
        defaults: BTreeMap<String, String>,
    },
    /// Map value schema, expanded as `<parent>.<key_placeholder>.<child>`.
    Map {
        /// Placeholder label rendered in docs for dynamic map keys.
        key_placeholder: &'static str,
        /// Child field docs from the map value schema.
        value_fields: Vec<FieldDoc>,
        /// Default values keyed by child field name.
        value_defaults: BTreeMap<String, String>,
    },
    /// List item schema, expanded as `<parent>.<index_placeholder>.<child>`.
    List {
        /// Placeholder label rendered in docs for dynamic list indexes.
        index_placeholder: &'static str,
        /// Child field docs from the list item schema.
        item_fields: Vec<FieldDoc>,
        /// Default values keyed by list item field name.
        item_defaults: BTreeMap<String, String>,
    },
}

/// Metadata for a single configuration field.
#[derive(Clone)]
pub struct FieldDoc {
    /// TOML key name for this field.
    pub toml_key: &'static str,
    /// Human-readable type name (e.g. "bool", "string", "integer").
    pub type_display: &'static str,
    /// Description extracted from the field's `///` doc comment.
    pub description: &'static str,
    /// For enum-typed fields, the list of valid TOML values.
    pub enum_values: Option<&'static [&'static str]>,
    /// Optional nested schema metadata for dotted-key expansion.
    pub nested: Option<NestedFieldDoc>,
}

/// Trait implemented by config structs via `#[derive(ConfigDoc)]`.
///
/// Provides all metadata needed to generate a configuration reference.
pub trait ConfigDocSchema: Default {
    /// TOML section name (e.g. `"general"`, `"behavior"`).
    fn section_name() -> &'static str;

    /// Section description extracted from the struct's doc comment.
    fn section_description() -> &'static str;

    /// Metadata for each field in this config section.
    fn field_docs() -> Vec<FieldDoc>;

    /// Default values for each field, serialized as TOML strings.
    ///
    /// Keys are TOML field names, values are the serialized default.
    /// Generated by constructing `Self::default()` and serializing each field.
    fn default_values() -> BTreeMap<String, String>;
}
