CREATE TABLE IF NOT EXISTS connections (
    client_id VARCHAR(64) PRIMARY KEY NOT NULL,
    tunnel_ws_id VARCHAR(64) NOT NULL,
    created DATETIME NOT NULL DEFAULT NOW(),
    updated DATETIME NOT NULL DEFAULT NOW()
);
