name: Tauri Build and Validate UI

on:
    push:
        branches: ["master"]
        paths:
            - packages/app/tauri/src/**
            - .github/workflows/tauri-build-and-test-ui.yml
            - "!**/*.md"
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v6

            - uses: dtolnay/rust-toolchain@stable

            - name: Generate config
              working-directory: packages/app/tauri
              run: cargo run --package moosicbox_app_create_config -- -o src/config.ts

            - name: Copy Files
              working-directory: packages/app/tauri
              shell: bash
              run: |
                  ./copy-files.sh

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: pnpm install
              working-directory: packages/app/tauri
              run: pnpm install

            - name: Check formatting
              uses: ./.github/actions/clippier
              with:
                  command: fmt
                  clippier-version: ""
                  workspace-path: packages/app/tauri
                  format-tools: biome

            - name: lint
              working-directory: packages/app/tauri
              run: pnpm lint

            - name: typecheck
              working-directory: packages/app/tauri
              run: pnpm typecheck
